spring.application.name=ecommerce-cloud
server.port=${PORT:8080}

spring.profiles.default=local

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.thymeleaf.cache=false
